name: Report Acceptance Criteria
run-name: Generate AC coverage report

# The report generation is performed ad hoc via manual invocation.
on: workflow_dispatch

env:
  glossaryURL: https://github.com/ameteiko/goreleaser/wiki/Glossary.md
  highlighter: ${{ github.workspace }}/scripts/bin/utils/report-highlighter/highlighter.py

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out LM source code
        uses: actions/checkout@v4
      - name: Check out report highlighter
        uses: actions/checkout@v4
        with:
          github-server-url: https://github.tools.sap
          repository: pandas/coverage-metrics
          path: scripts
          token: ${{secrets.SAP_GITHUBTOOLS_PAT}}
      - name: Prepare the highlighter utility
        run: |
          chmod a+x $highlighter
      - name: Genarate a report
        run: cd ${{ github.workspace }}/tests/e2e_test && make e2e-coverage | $highlighter $glossaryURL
